name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - uses: actions/checkout@v4

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and push Docker image in a single step
    - name: Build and Push Docker image
      run: |
        IMAGE_TAG=$(date +%s)
        IMAGE_NAME=karthick51/fashion-finder:$IMAGE_TAG
        echo "Building Docker image $IMAGE_NAME"
        docker build -t $IMAGE_NAME .
        echo "Pushing Docker image $IMAGE_NAME"
        docker push $IMAGE_NAME
